project:
  type: default
  output-dir: _output

format:
  revealjs:
    theme: default
    slide-number: c/t
    show-slide-number: all
    footer: "Peng Zhang, PhD | CIMS Global | Conference Name | YYYY-MM-DD"
    logo: ""
    transition: fade
    chalkboard: false
    code-fold: false
    highlight-style: github
    fig-align: center
    width: 1600
    height: 900
