project:
  type: default

execute:
  enabled: false

format:
  beamer:
    aspectratio: 169
    theme: metropolis
    fonttheme: professionalfonts
    include-in-header:
      text: |
        \setbeamercolor{frametitle}{bg=black, fg=white}
        \setbeamercolor{progress bar}{fg=orange}
        \setbeamercolor{title separator}{fg=orange}
        \setbeamerfont{title}{size=\Large, series=\bfseries}
        \setbeamerfont{subtitle}{size=\normalsize}
        \setbeamerfont{frametitle}{size=\normalsize, series=\bfseries}
        \metroset{progressbar=frametitle, sectionpage=progressbar, block=fill}
