project:
  type: default
  output-dir: _output

format:
  revealjs:
    theme: default
    slide-number: c/t
    show-slide-number: all
    footer: "Peng Zhang, PhD | CIMS Global | GenAI in Pharma | 2026-06-16"
    logo: ""
    transition: fade
    chalkboard: false
    code-fold: false
    highlight-style: github
    fig-align: center
    width: 1600
    height: 900
