project:
  type: default

execute:
  enabled: false

format:
  beamer:
    aspectratio: 169
    theme: metropolis
    fonttheme: professionalfonts
    include-in-header:
      text: |
        \setbeamercolor{frametitle}{bg=white, fg=black}
        \setbeamercolor{background canvas}{bg=white}
        \setbeamercolor{normal text}{fg=black}
        \setbeamercolor{progress bar}{fg=black!30}
        \setbeamercolor{title separator}{fg=black!30}
        \setbeamercolor{alerted text}{fg=black}
        \setbeamerfont{title}{size=\LARGE, series=\bfseries}
        \setbeamerfont{subtitle}{size=\normalsize, series=\normalfont}
        \setbeamerfont{frametitle}{size=\large, series=\bfseries}
        \setbeamerfont{normal text}{size=\normalsize}
        \metroset{progressbar=none, sectionpage=none, block=transparent}
